export const notifications = [
    {username: 'thestar_lord, thematerial__', subject: 'liked your post'},
    {username: 'pepperpots', subject: 'liked your post'},
    {username: '_tonystark__the__ironman____', subject: 'liked your post'},
    {username: 'n8goodmen', subject: ' and other 5 liked your post'},
    {username: 'thehawlk_eye__0_0__', subject: 'tagged a photo with you'},
    {username: 'dornamaareef_008', subject: 'commented on your post'},
    {username: 'natasharamanolf', subject: ' and 2 others liked your post'},
    {username: 'dr_strange', subject: 'liked your post'},
    {username: 'billgates', subject: 'uploaded a new video'},
    {username: '_the_bad_boys_quotes____', subject: 'started live streaming'},
    {username: 'mathews_herc', subject: 'liked your post'},
    {username: 'i_am_vision', subject: 'liked your post'},
    {username: 'mathews_herc', subject: 'liked your post'},
    {username: 'mathews_herc', subject: 'liked your post'},
    {username: 'ninjaking', subject: 'liked your post'},
    {username: 'imogenguinness', subject: 'commented on your post'},
    {username: 'mathews_herc', subject: 'liked your post'},
    {username: 'iamgroooot___', subject: 'liked your post'},
    {username: 'thestar_lord', subject: ' and two others liked your post'},
    {username: 'mathews_herc', subject: 'liked your post'},
    {username: 'happy345', subject: 'commented on your post'},
    {username: 'iamgroooot___', subject: 'liked your post'},
    {username: 'warmachine001', subject: 'liked your post'},
    {username: 'dornamaareef_008', subject: 'commented on your post'},
    {username: 'natasharamanolf', subject: ' and 2 others liked your post'},
    {username: 'dr_strange', subject: 'liked your post'},
    {username: 'billgates', subject: 'uploaded a new video'},
    {username: '_the_bad_boys_quotes____', subject: 'started live streaming'},
    {username: 'mathews_herc', subject: 'liked your post'},
    {username: 'i_am_vision', subject: 'liked your post'},
    {username: 'pepperpots', subject: 'liked your post'},
    {username: '_tonystark__the__ironman____', subject: 'liked your post'},
    {username: '_tonystark__the__ironman____', subject: 'liked your post'},
    {username: '_tonystark__the__ironman____', subject: 'liked your post'},
    {username: '_tonystark__the__ironman____', subject: 'liked your post'},
    {username: 'natasharamanolf', subject: ' and 2 others liked your post'},
    {username: 'dr_strange', subject: 'liked your post'},
    {username: 'billgates', subject: 'uploaded a new video'},
]